namespace: schaurs
name: oac
version: "1.0.0"
readme: README.md
description: "Configuration as Code collection for Ansible Automation Platform"

authors:
  - "Your Name <your.email@example.com>"

dependencies: {}

license:
  - "GPL-2.0-or-later"

tags:
  - configuration
  - automation
  - infrastructure

repository: "https://github.com/schaurs/OaC"
documentation: "https://github.com/schaurs/OaC"
homepage: "https://github.com/schaurs/OaC"
issues: "https://github.com/schaurs/OaC/issues"

server: https://sandbox-aap-suresh-chaurasia-dev.apps.rm3.7wse.p1.openshiftapps.com/api/galaxy/

build_ignore:
  - "*.tar.gz"
  - ".git*"
  - ".vscode"
  - "tests/output"