---
- name: Hello Playbook
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Say Hello
      debug:
        msg: "Say Hello, World!"
    - name: Debug webhook payload
      debug:
        msg: "{{ webhook_payload }}"
