---
# AAP Controller Credentials
controller_username: suresh
controller_oauth_token: TiAUYjrMm9vgz7HodvMQZATZM9RGN6

# GitHub export settings
github_remote_url: "https://github.com/schaurs/OaC.git"
github_token: "YOUR_GITHUB_TOKEN_HERE"